---
- name: authentik - configure freeipa
  ansible.builtin.include_tasks: freeipa_service_bind.yml
  vars:
    freeipa_service_bind_sysaccount_dn: "{{ authentik_ldap_bind_dn }}"
    freeipa_service_bind_sysaccount_pass: "{{ authentik_ldap_bind_pw }}"
    freeipa_service_bind_group_name: "{{ authentik_ldap_access_group }}"
  args:
    apply:
      tags: authentik
  tags: authentik
