---
- name: freeipa - include_vars
  include_vars:
    file: ../defaults/main.yml
  no_log: true

- name: freeipa - manage user '{{ user.key }}'
  community.general.ipa_user:
    uid: "{{ user.key }}"
    givenname: "{{ user.value.givenname }}"
    sn: "{{ user.value.sn }}"
    password: "{{ user.value.password }}"
    update_password: "{{ user.value.update_password | default('on_create') }}"
    state: "{{ user.value.state | default('present') }}"
    ipa_host: "{{ inventory__ldap_domain }}"
    ipa_pass: "{{ freeipa_admin_password }}"
  no_log: true

- name: freeipa - set attributes for user '{{ user.key }}'
  community.general.ldap_attrs:
    dn: uid={{ user.key }},cn=users,cn=accounts,{{ inventory__ldap_base_dn }}
    attributes: "{{ item.name }}={{ item.value }}"
    state: "{{ item.state | default('present') }}"
    server_uri: ldap://{{ inventory__ldap_domain }}/
    bind_dn: cn=Directory Manager
    bind_pw: "{{ freeipa_ds_password }}"
    start_tls: yes
    validate_certs: no
  loop: "{{ user.value.attrs }}"
  when: user.value.attrs | default(false)

- name: freeipa - manage user groups '{{ user.key }}'
  community.general.ipa_group:
    cn: "{{ item | default('ipausers') }}"
    user: "{{ user.key }}"
    append: yes
    state: present
    ipa_host: "{{ inventory__ldap_domain }}"
    ipa_pass: "{{ freeipa_admin_password }}"
  loop: "{{ user.value.groups }}"
  when: user.value.groups | default(false)
