---
- name: freeipa - include_vars
  include_vars:
    file: ../defaults/main.yml

- name: freeipa - manage user '{{ user.uid }}'
  ipa_user:
    uid: "{{ user.uid }}"
    givenname: "{{ user.givenname }}"
    sn: "{{ user.sn }}"
    password: "{{ user.password }}"
    update_password: "{{ user.update_password | default('on_create') }}"
    state: "{{ user.state | default('present') }}"
    ipa_host: "{{ freeipa_hostname }}"
    ipa_pass: "{{ freeipa_admin_password }}"
  no_log: true

- name: freeipa - set attributes for user '{{ user.uid }}'
  ldap_attr:
    dn: "uid={{ user.uid }},cn=users,cn=accounts,{{ freeipa_base_dn }}"
    name: "{{ item.name }}"
    values: "{{ item.value }}"
    state: "{{ item.state | default('present') }}"
    server_uri: "ldap://{{ freeipa_hostname }}/"
    bind_dn: "cn=Directory Manager"
    bind_pw: "{{ freeipa_ds_password }}"
    start_tls: yes
    validate_certs: no
  loop: "{{ user.attrs }}"
  when: user.attrs | default(false)
