---
- name: freeipa - include_vars
  ansible.builtin.include_vars: ../defaults/main.yml
  no_log: true

- name: freeipa - ensure service account is present
  community.general.ldap_entry:
    dn: "{{ freeipa_service_bind_sysaccount_dn | default('uid=sudo,cn=sysaccounts,cn=etc,dc=home,dc=devmem,dc=ru') }}"
    objectClass:
      - account
      - simplesecurityobject
    attributes:
      userPassword: "{{ freeipa_service_bind_sysaccount_pass | default('str0ng_passw0rd') }}"
      passwordExpirationTime: "20380119031407Z"
      nsIdleTimeout: "0"
    state: present
    server_uri: ldap://{{ inventory__ldap_domain }}/
    bind_dn: cn=Directory Manager
    bind_pw: "{{ freeipa_ds_password }}"
    start_tls: true
    validate_certs: false
  delegate_to: localhost
  become: false

- name: freeipa - ensure service group is present
  community.general.ipa_group:
    name: "{{ freeipa_service_bind_group_name | default('ipausers') }}"
    state: present
    ipa_host: "{{ inventory__ldap_domain }}"
    ipa_pass: "{{ freeipa_admin_password }}"
  delegate_to: localhost
  become: false
