---
- name: heimdall - start
  docker_container:
    name: heimdall
    image: linuxserver/heimdall:latest
    pull: yes
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/heimdall/config:/config"
    networks:
      - name: traefik
    networks_cli_compatible: yes
    labels:
      traefik.enable: "true"
      traefik.http.routers.heimdall.rule: "HostRegexp(`mgmt{fqdn:(.home.devmem.ru)?}`)"
      traefik.http.routers.heimdall.entrypoints: "websecure"
      traefik.http.routers.heimdall.tls: "true"
    restart_policy: unless-stopped
    state: started
  tags: heimdall
