---
- name: vaultwarden
  include_tasks: vaultwarden.yml
  tags: vaultwarden

- name: freeipa
  include_tasks: freeipa.yml
  tags: freeipa

- name: heimdall
  include_tasks: heimdall.yml
  tags: heimdall

- name: portainer
  include_tasks: portainer.yml
  tags: portainer

- name: unifi
  include_tasks: unifi.yml
  tags: unifi

- name: unms
  include_tasks: unms.yml
  tags: unms
