---
- name: freeipa
  ansible.builtin.include_tasks: freeipa.yml
  tags: freeipa

- name: vaultwarden
  ansible.builtin.include_tasks: vaultwarden.yml
  tags: vaultwarden

- name: portainer
  ansible.builtin.include_tasks: portainer.yml
  tags: portainer

- name: unifi
  ansible.builtin.include_tasks: unifi.yml
  tags: unifi

- name: authentik
  ansible.builtin.include_tasks: authentik.yml
  tags: authentik

- name: dex
  ansible.builtin.include_tasks: dex.yml
  tags: dex

# - name: vault
#   ansible.builtin.include_tasks: vault.yml
#   tags: vault

# - name: unms
#   ansible.builtin.include_tasks: unms.yml
#   tags: unms

# - name: heimdall
#   ansible.builtin.include_tasks: heimdall.yml
#   tags: heimdall
