---
- name: unifi - start
  docker_container:
    name: unifi
    image: linuxserver/unifi-controller:latest
    pull: yes
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8081:8081"
      - "8443:8443"
      - "8843:8843"
      - "8880:8880"
      - "6789:6789"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ app_path }}/unifi/config:/config"
    restart_policy: unless-stopped
    state: started
  tags: unifi
