---
- name: unms - start
  docker_container:
    name: unms
    image: nico640/docker-unms:latest
    pull: yes
    ports:
      - "2055:2055/udp"
    env:
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/unms/config:/config"
    networks:
      - name: traefik
    networks_cli_compatible: yes
    labels:
      traefik.enable: "true"
      traefik.http.routers.unms.rule: "HostRegexp(`unms{fqdn:(.home.devmem.ru)?}`)"
      traefik.http.routers.unms.entrypoints: "websecure"
      traefik.http.routers.unms.tls: "true"
      traefik.http.services.unms.loadbalancer.server.port: "443"
      traefik.http.services.unms.loadbalancer.server.scheme: "https"
    restart_policy: unless-stopped
    state: started
  tags: unms
