---
- include_tasks: util_vm_list.yml

- block:
    - name: "{{ hostname }} - Create"
      command: >
        qm create {{ vmid }}
          --pool {{ resourse_pool }}
          --ostype {{ vm_ostype }}
          --name {{ hostname }}
          --description "{{ comment }}"
          --agent 1,fstrim_cloned_disks=1
          --cores {{ cores }}
          --memory {{ mem }}
          --net0 virtio,bridge={{ net_br }},tag={{ net_vlan }}
          --ipconfig0 gw={{ net_gw }},ip={{ net_ip }}/{{ net_cidr }}
          --nameserver {{ net_dns }}
          --searchdomain {{ net_domain }}
          --sshkeys "{{ ssh_keys }}"
          {{ vm_other_options | default('', true) }}

    - name: "{{ hostname }} - Set default user password"
      command: >
        qm set {{ vmid }}
          --cipassword {{ user_pass }}
      no_log: true

    - name: "{{ hostname }} - Import qcow2 image"
      command: >
        qm importdisk {{ vmid }} {{ vm_image }} {{ disk_storage }}

    - name: "{{ hostname }} - Confige hardware"
      command: >
        qm set {{ vmid }}
          --scsihw virtio-scsi-pci
          --scsi0 {{ disk_storage }}:vm-{{ vmid }}-disk-0,discard=on
          --ide2 {{ disk_storage }}:cloudinit
          --bootdisk scsi0
          --boot c
          --serial0 socket
          --vga serial0

    - name: "{{ hostname }} - Resize disk"
      command: >
        qm resize {{ vmid }} scsi0 {{ disk_size }}G
  when: vmid_string not in vm_list.stdout
