---
- name: include util_resource_facts.yml
  ansible.builtin.include_tasks: util_resources_facts.yml

- name: resource destroy
  when: pve_resource_exists
  block:
    - name: "{{ hostname }} - Destroy"
      ansible.builtin.shell: >
        qm stop {{ vmid }} && qm destroy {{ vmid }}
      changed_when: true
      when: resource_type == "vm"

    - name: "{{ hostname }} - Destroy"
      ansible.builtin.shell: >
        pct stop {{ vmid }}; pct destroy {{ vmid }}
      changed_when: true
      when: resource_type == "ct"

- name: Delete Resource Pool
  ansible.builtin.command: >
    pvesh delete /pools/{{ resourse_pool }}
  register: _delete_pool
  changed_when: _delete_pool.rc == 0
  failed_when: _delete_pool.rc >= 1 and "is not empty" not in _delete_pool.stderr
  when: pve_pool_exists
