---
- name: include util_resource_facts.yml
  ansible.builtin.include_tasks: util_resources_facts.yml

- name: shutdown
  when:
    - pve_resource_exists
    - pve_resource_exists[0].status != 'stopped'
  block:
    - name: "{{ hostname }} - Shutdown"
      ansible.builtin.shell: >
        qm shutdown {{ vmid }} && qm wait {{ vmid }} -timeout 60
      changed_when: true
      when: resource_type == 'vm'

    - name: "{{ hostname }} - Shutdown"
      ansible.builtin.shell: >
        pct shutdown {{ vmid }}
      changed_when: true
      when: resource_type == 'ct'
