---
- name: pihole - restart
  community.docker.docker_container:
    name: pihole
    state: started
    restart: yes
  when: not pihole_start.changed

- name: pihole - update lists
  ansible.builtin.command: >
    docker exec pihole sh -c '/usr/local/sbin/pihole-updatelists > /dev/null 2>&1'
