---
kind: pipeline
name: build

steps:
  - name: pihole
    image: plugins/docker
    settings:
      registry: registry.home.devmem.ru
      repo: registry.home.devmem.ru/pihole
      dockerfile: ./roles/homelab_svc/pihole/files/pihole.Dockerfile
      cache_from: registry.home.devmem.ru/pihole:latest
      tags:
        - latest
