---
kind: pipeline
name: build images

trigger:
  event:
    - cron

steps:
  - name: jenkins
    image: plugins/docker
    settings:
      registry: registry.home.devmem.ru
      repo: registry.home.devmem.ru/jenkins
      dockerfile: ./roles/homelab_svc/dev/files/jenkins/jenkins.Dockerfile
      context: ./roles/homelab_svc/dev/files/jenkins
      cache_from: registry.home.devmem.ru/jenkins:latest
      tags:
        - latest

  - name: pihole
    image: plugins/docker
    settings:
      registry: registry.home.devmem.ru
      repo: registry.home.devmem.ru/pihole
      dockerfile: ./roles/homelab_svc/pihole/files/pihole.Dockerfile
      context: ./roles/homelab_svc/pihole/files
      cache_from: registry.home.devmem.ru/pihole:latest
      tags:
        - latest
