---
kind: pipeline
type: docker
name: default

steps:
- name: pihole
  image: plugins/docker
  settings:
    repo: registry.home.devmem.ru/pihole
    registry: registry.home.devmem.ru
    dockerfile: ./roles/homelab_svc/pihole/files/pihole.Dockerfile
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - latest
