repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        args: [--strict]
        exclude: .pre-commit-config|.github/|files/|Definitions/|vault
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v6.8.2
    hooks:
      - id: ansible-lint
