repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.0.0
  hooks:
    - id: end-of-file-fixer
    - id: check-merge-conflict
    - id: mixed-line-ending
    - id: trailing-whitespace
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.23.0
  hooks:
    - id: yamllint
      args: [--strict]
      exclude: .pre-commit-config|files/|Definitions/|vault
- repo: https://github.com/ansible/ansible-lint.git
  rev: v4.2.0
  hooks:
    - id: ansible-lint
      entry: ansible-lint
