---
- name: Provision host
  hosts: spsrv
  gather_facts: false

  vars:
    resource_type: ct
    vmid: 502
    hostname: spnas
    comment: spnas
    cores: 4
    mem: 4096
    disk_size: 20
    net_ip: 192.168.10.11
    net_vlan: 10
    net_gw: 192.168.10.1
    net_dns: 192.168.10.1
    net_domain: "{{ inventory__homelab_domain }}"
    ct_other_options: >
      --onboot 1
      --mp0 volume=/mnt/storage/downloads,mp=/docker/spnas/data/downloads,replicate=0
      --mp1 volume=/mnt/tank0/ds0/backups/timemachine,mp=/docker/spnas/data/backups/timemachine,replicate=0
      --mp2 volume=/mnt/tank0/ds0/backups/windows,mp=/docker/spnas/data/backups/windows,replicate=0
      --mp3 volume=/mnt/tank0/ds0/cloud,mp=/docker/spnas/data/cloud,replicate=0
      --mp4 volume=/mnt/tank0/ds0/docs,mp=/docker/spnas/data/docs,replicate=0
      --mp5 volume=/mnt/tank0/ds0/minio,mp=/docker/spnas/data/minio,replicate=0
      --mp6 volume=/mnt/tank0/ds0/public,mp=/docker/spnas/data/public,replicate=0
      --mp7 volume=/mnt/tank0/ds0/pvmhome,mp=/docker/spnas/data/pvmhome,replicate=0

  roles:
    - { role: pve_manager }
    - { role: portainer_api }


- name: Apply host-specific roles
  hosts: spnas
  gather_facts: false

  roles:
    - { role: homelab_svc/spnas, tags: [spnas, svc] }
