---
- hosts: all
  gather_facts: no

- ansible.builtin.import_playbook: deploy_homelab_set_static_dns.yml
- ansible.builtin.import_playbook: deploy_homelab_svc_mgmt.yml
- ansible.builtin.import_playbook: deploy_homelab_manage_users.yml
# - ansible.builtin.import_playbook: deploy_homelab_svc_pihole.yml
- ansible.builtin.import_playbook: deploy_homelab_svc_rp.yml
- ansible.builtin.import_playbook: deploy_homelab_svc_mail.yml
- ansible.builtin.import_playbook: deploy_homelab_svc_stats.yml
- ansible.builtin.import_playbook: deploy_homelab_svc_dev.yml
- ansible.builtin.import_playbook: deploy_homelab_svc_spnas.yml
- ansible.builtin.import_playbook: deploy_homelab_svc_plex.yml
# - ansible.builtin.import_playbook: deploy_homelab_svc_projects.yml
- ansible.builtin.import_playbook: ha.yml
- ansible.builtin.import_playbook: deploy_homelab_upgrade_packages.yml
