---
- hosts: ubnt-erx-krs
  strategy: linear
  gather_facts: no

  vars:
    dn: "{{ inventory__homelab_domain }}"
    ip_plex: 192.168.10.10
    ip_spnas: 192.168.10.11
    ip_dev: 192.168.10.12
    ip_mgmt: 192.168.11.2
    ip_stats: 192.168.12.98
    ip_mail: 192.168.12.250
    ip_rp: 192.168.12.254
    ip_pihole: 192.168.16.2
    ip_projects: 192.168.12.251
    ip_ha: 192.168.20.176
    ip_gw_wg: 192.168.13.2
    dns_entries:
      - { alias: "plex", inet: "{{ ip_plex }}" }
      - { alias: "traefik-plex", inet: "{{ ip_plex }}" }
      - { alias: "ombi", inet: "{{ ip_plex }}" }
      - { alias: "tautulli", inet: "{{ ip_plex }}" }

      - { alias: "spnas", inet: "{{ ip_spnas }}" }
      - { alias: "traefik-spnas", inet: "{{ ip_spnas }}" }
      - { alias: "deluge", inet: "{{ ip_spnas }}" }
      - { alias: "jackett", inet: "{{ ip_spnas }}" }
      - { alias: "monitorrent", inet: "{{ ip_spnas }}" }
      - { alias: "sonarr", inet: "{{ ip_spnas }}" }
      - { alias: "radarr", inet: "{{ ip_spnas }}" }
      - { alias: "lidarr", inet: "{{ ip_spnas }}" }
      - { alias: "bazarr", inet: "{{ ip_spnas }}" }
      - { alias: "cloud", inet: "{{ ip_spnas }}" }
      - { alias: "prowlarr", inet: "{{ ip_spnas }}" }
      - { alias: "flaresolverr", inet: "{{ ip_spnas }}" }

      - { alias: "dev", inet: "{{ ip_dev }}" }
      - { alias: "traefik-dev", inet: "{{ ip_dev }}" }
      - { alias: "code", inet: "{{ ip_dev }}" }
      - { alias: "git", inet: "{{ ip_dev }}" }
      - { alias: "drone", inet: "{{ ip_dev }}" }
      - { alias: "registry", inet: "{{ ip_dev }}" }
      - { alias: "jenkins", inet: "{{ ip_dev }}" }

      - { alias: "mgmt", inet: "{{ ip_mgmt }}" }
      - { alias: "traefik-mgmt", inet: "{{ ip_mgmt }}" }
      - { alias: "portainer", inet: "{{ ip_mgmt }}" }
      - { alias: "unifi", inet: "{{ ip_mgmt }}" }
      - { alias: "unms", inet: "{{ ip_mgmt }}" }
      - { alias: "bw", inet: "{{ ip_mgmt }}" }
      - { alias: "ipa", inet: "{{ ip_mgmt }}" }
      - { alias: "ldap", inet: "{{ ip_mgmt }}" }
      - { alias: "vault", inet: "{{ ip_mgmt }}" }

      - { alias: "stats", inet: "{{ ip_stats }}" }
      - { alias: "traefik-stats", inet: "{{ ip_stats }}" }
      - { alias: "nms", inet: "{{ ip_stats }}" }
      - { alias: "grafana", inet: "{{ ip_stats }}" }
      - { alias: "influxdb", inet: "{{ ip_stats }}" }
      - { alias: "loki", inet: "{{ ip_stats }}" }
      - { alias: "prometheus", inet: "{{ ip_stats }}" }

      - { alias: "mail", inet: "{{ ip_mail }}" }
      - { alias: "traefik-mail", inet: "{{ ip_mail }}" }

      - { alias: "rp", inet: "{{ ip_rp }}" }

      - { alias: "pihole", inet: "{{ ip_pihole }}" }
      - { alias: "traefik-pihole", inet: "{{ ip_pihole }}" }

      - { alias: "projects", inet: "{{ ip_projects }}" }
      - { alias: "traefik-projects", inet: "{{ ip_projects }}" }

      - { alias: "ha", inet: "{{ ip_ha }}" }
      - { alias: "traefik-ha", inet: "{{ ip_ha }}" }
      - { alias: "esp", inet: "{{ ip_ha }}" }
      - { alias: "grocy", inet: "{{ ip_ha }}" }

      - { alias: "gw-wg", inet: "{{ ip_gw_wg }}" }

  tasks:
    - name: Set static DNS mapping
      edgeos_config:
        lines:
          - set system static-host-mapping host-name {{ dns_entry.alias }}.{{ dn }} inet {{ dns_entry.inet }}
          - set system static-host-mapping host-name {{ dns_entry.alias }}.{{ dn }} alias {{ dns_entry.alias }}
      loop_control:
        loop_var: dns_entry
      loop: "{{ dns_entries }}"
      tags: [never, dns]

# - name: Delete static DNS mapping
#   edgeos_config:
#     lines:
#       - delete system static-host-mapping host-name {{ dns_entry.alias }}.{{ dn }}
#   loop_control:
#     loop_var: dns_entry
#   loop: "{{ dns_entries }}"
#   tags: [never, dns]
