---
- hosts: spsrv
  gather_facts: no

  vars:
    resource_type: ct
    vmid: 203
    hostname: dev
    comment: Development
    cores: 2
    mem: 2048
    disk_size: 20
    net_ip: 192.168.10.12
    net_vlan: 10
    net_gw: 192.168.10.1
    net_dns: 192.168.10.1
    net_domain: "{{ inventory__homelab_domain }}"
    ct_other_options: >
      --onboot 1

  roles:
    - pve_manager
    - portainer_api


- hosts: dev
  gather_facts: no

  roles:
    - {role: homelab_svc/dev, tags: [dev, svc]}
