---
- name: Manage FreeIPA users
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: manage users
      ansible.builtin.include_tasks: roles/homelab_svc/mgmt/tasks/freeipa_user.yml
      loop_control:
        loop_var: user
      loop: "{{ lookup('dict', inventory__ldap_users) }}"
      args:
        apply:
          tags: [never, manage_users]
      tags: [never, manage_users]
      no_log: true
