---
- name: Provision host
  hosts: spsrv
  gather_facts: false

  vars:
    resource_type: ct
    vmid: 207
    hostname: pihole
    comment: Pi-hole
    cores: 1
    mem: 512
    disk_size: 4
    net_ip: 192.168.16.2
    net_vlan: 16
    net_gw: 192.168.16.1
    net_dns: 192.168.16.1
    net_domain: "{{ inventory__homelab_domain }}"
    ct_other_options: >
      --onboot 1

  roles:
    - pve_manager
    - portainer_api


- name: Apply host-specific roles
  hosts: pihole
  gather_facts: false

  roles:
    - { role: homelab_svc/pihole, tags: [pihole, svc] }
