---
- hosts: spsrv
  gather_facts: no

  vars:
    resource_type: ct
    vmid: 203
    hostname: dev
    comment: Development
    cores: 2
    mem: 2048
    disk_size: 8
    net_ip: 192.168.10.12
    net_vlan: 10
    net_gw: 192.168.10.1
    net_dns: 192.168.10.1
    net_domain: home.devmem.ru
    ct_other_options: >
      --onboot 1

  roles:
    - vm_manager_single


- hosts: dev
  gather_facts: no

  roles:
    - {role: homelab_svc/dev, tags: [dev, svc]}
