---
- hosts: linux
  gather_facts: no

  tasks:
    - name: Upgrade packages
      package:
        update_cache: yes
        state: latest
        name: "*"
      become: true
      tags: upgrade_packages
