---
- hosts: spmaxi
  gather_facts: no

  vars_files:
    - vars.yml

  vars:
    # WARNING! ALARMA! ВМ исчезнут без следа при значении true!
    vm_destroy:

    # Завершить работу ВМ
    vm_shutdown:

    # Сколько нужно создать ВМ (от 1 до 9)
    vm_count: 3
    vm_index_list: "{{ range(0, lookup('vars', 'vm_count')) | list }}"

  pre_tasks:
    - name: Get resource pools list from Proxmox
      command: >
        pvesh get /pools  --output-format yaml
      register: proxmox_pool_list
      changed_when: false

    - name: Get VMs list from Proxmox
      command: >
        pvesh get /cluster/resources --type vm  --output-format yaml
      register: proxmox_vm_list
      changed_when: false

  tasks:
    - block:
        - include_tasks: vm_start.yml
        - include_tasks: vm_create.yml
      when: >
        not vm_shutdown |default(false) |bool and
        not vm_destroy |default(false) |bool

    - include_tasks: vm_shutdown.yml
      when: >
        vm_shutdown |default(false) |bool and
        not vm_destroy |default(false) |bool

    - include_tasks: vm_destroy.yml
      when: vm_destroy |default(false) |bool
