---
- hosts: all
  gather_facts: false

- ansible.builtin.import_playbook: vps.yml
- ansible.builtin.import_playbook: pve.yml
- ansible.builtin.import_playbook: gw_wg.yml
- ansible.builtin.import_playbook: ha.yml
- ansible.builtin.import_playbook: deploy_homelab.yml
