---
- hosts: spmaxi
  gather_facts: no

  vars_files:
    - vars.yml

  vars:
    # Сколько нужно создать ВМ (от 1 до 9)
    vm_count: 4
    vm_index_list: "{{ range(0, lookup('vars', 'vm_count')) | list }}"

  pre_tasks:
    - name: Get resource pools list from Proxmox
      command: >
        pvesh get /pools  --output-format yaml
      register: proxmox_pool_list
      changed_when: false
      tags: always

    - name: Get VMs list from Proxmox
      command: >
        pvesh get /cluster/resources --type vm  --output-format yaml
      register: proxmox_vm_list
      changed_when: false
      tags: always

  tasks:
    - include_tasks:
        file: vm_create.yml
        apply:
          tags: create
      tags: create

    - include_tasks: vm_start.yml
      tags: start

    - include_tasks: vm_dyn_inventory.yml
      tags: dyn_inventory

    - include_tasks: vm_shutdown.yml
      tags: [never, shutdown]

    - include_tasks: vm_destroy.yml
      tags: [never, destroy]


- hosts: k8s
  become: yes

  pre_tasks:
    - name: Wait up to 10 minutes for yum process to exit
      wait_for:
        path: /var/run/yum.pid
        state: absent
        timeout: 600

    - include_tasks: k8s_docker.yml

  roles:
    - role: geerlingguy.kubernetes
      vars:
        kubernetes_allow_pods_on_master: false
