---
- hosts: spsrv
  gather_facts: no

  vars:
    resource_type: ct
    vmid: 5501
    hostname: test-ct
    net_ip: 192.168.13.50
    ct_other_options: >
      --swap 0
    lxc_options:
      - "lxc.cgroup.devices.allow: c 226:* rwm"
      - "lxc.mount.entry: /dev/dri dev/dri none bind,create=dir"

  roles:
    - pve_manager
