---
- hosts: spsrv
  gather_facts: no

  vars:
    resource_type: vm
    vmid: 5601
    hostname: test-vm
    net_ip: 192.168.13.60
    vm_other_options: >
      --onboot 1

  roles:
    - pve_manager
