---
- hosts: proxmox
  gather_facts: no

  vars:
    os_images:
      - "https://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
      - "https://cdimage.debian.org/images/cloud/bullseye/latest/debian-11-genericcloud-amd64.qcow2"
      - "https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-2111.qcow2"
    qcow2_path: /mnt/pve/spsrv-proxmox/template/qcow2

  tasks:
    - name: Download cloud images
      get_url:
        url: "{{ item }}"
        dest: "{{ qcow2_path }}/{{ item | basename }}"
      loop: "{{ os_images }}"
      run_once: true
