---
- hosts: spsrv
  gather_facts: no

  vars:
    resource_type: vm
    vmid: 5777
    hostname: templatevm
    net_ip: 192.168.13.77
    storage_path: /mnt/tank0/ds0/proxmox
    templates_path: "{{ storage_path }}/template/qcow2"
    vm_image: "{{ templates_path }}/CentOS-7-x86_64-GenericCloud-2111.qcow2"
    updated_image_name: "{{ templates_path }}/CentOS-7-x86_64-GenericCloud-updated.qcow2"

  roles:
    - pve_manager

  tasks:
    - name: Set facts
      set_fact:
        vmid: "{{ vmid }}"
        storage_path: "{{ storage_path }}"
        updated_image_name: "{{ updated_image_name }}"


- hosts: templatevm
  gather_facts: no

  handlers:
    - name: run script
      command: /tmp/sys_prep_cloud.sh
      async: 1
      poll: 0
      become: yes

  tasks:
    - name: Wait for yum process to exit (cloud-init updates)
      wait_for:
        path: /var/run/yum.pid
        state: absent
        timeout: 600

    - name: Copy script
      copy:
        src: files/sys_prep_cloud.sh
        dest: /tmp
        mode: 0755
      notify: run script


- hosts: spsrv
  gather_facts: no

  tasks:
    - name: Check that VM is stopped
      command: >
        qm status {{ vmid }}
      register: vm_status
      retries: 5
      delay: 5
      until: "'stopped' in vm_status.stdout"
      changed_when: false

    - block:
        - name: Convert disk to qcow2 (full-size)
          command: >
            qm move_disk {{ vmid }} scsi0 local-spsrv-proxmox --format qcow2 --delete
          changed_when: true

        - name: Delete old template
          file:
            path: "{{ updated_image_name }}"
            state: absent

        - name: Convert qcow2 to template (shrinked)
          command: >
            qemu-img convert -O qcow2 -c
            {{ storage_path }}/images/{{ vmid }}/vm-{{ vmid }}-disk-0.qcow2
            {{ updated_image_name }}
          changed_when: true

        - name: Destroy VM
          command: >
            qm destroy {{ vmid }}
          changed_when: true
      when: "'stopped' in vm_status.stdout"
