---
- name: Provision VM
  hosts: spsrv
  gather_facts: false

  vars:
    resource_type: vm
    vmid: 5601
    hostname: test-vm
    net_ip: 192.168.13.60
    vm_other_options: >
      --onboot 1

  roles:
    - pve_manager


- name: Test VM
  hosts: test-vm
  gather_facts: true

  pre_tasks:
    - name: Wait for cloud-init to finish
      ansible.builtin.wait_for:
        path: /var/lib/cloud/instance/boot-finished

  tasks:
    - name: print facts
      ansible.builtin.debug:
        var: ansible_facts
