---
- hosts: vps
  gather_facts: yes

  vars:
    sshd_port: 51858
    snmp_syslocation: sale-dedic.com
    sshd_password_authentication: 'no'
    sshd_authentication_methods: publickey

  roles:
    - { role: common/packages, tags: [vps, packages] }
    - { role: common/zsh, tags: [vps, zsh] }
    - { role: common/mc, tags: [vps, mc] }
    - { role: common/nano, tags: [vps, nano] }
    - { role: common/motd, tags: [vps, motd] }
    - { role: common/sshd, tags: [vps, sshd] }
    - { role: common/snmp, tags: [vps, snmp] }
    - { role: common/wireguard, tags: [vps, wireguard] }
    - { role: vps, tags: [vps, vps_specific] }
