---
- name: librenms - setup_database
  ansible.builtin.command: >
    docker exec librenms setup_database
  register: result
  retries: 3
  delay: 10
  until: result is not failed
  changed_when: '"Nothing to migrate" not in result.stdout'
  failed_when: >
    ("Permission denied" in result.stdout) or
    ("Could not connect to database" in result.stdout)

- name: librenms - restart
  community.docker.docker_container:
    name: librenms
    state: started
    restart: true
  no_log: true
  when: not librenms_start.changed

- name: influxdb - restart
  community.docker.docker_container:
    name: influxdb
    state: started
    restart: true
  when: not influxdb_start.changed

- name: mosquitto - restart
  community.docker.docker_container:
    name: mosquitto
    state: started
    restart: true
  when: not mosquitto_start.changed

- name: grafana - restart
  community.docker.docker_container:
    name: grafana
    state: started
    restart: true
  when: not grafana_start.changed

- name: prometheus - restart
  community.docker.docker_container:
    name: prometheus
    state: started
    restart: true
  when: not prometheus_start.changed
