---
- name: grafana - start
  docker_container:
    name: grafana
    image: "{{ grafana_image }}"
    pull: yes
    ports:
      - "3000:3000"
    volumes:
      - "{{ app_path }}/grafana/config:/var/lib/grafana"
    networks:
      - name: traefik
    networks_cli_compatible: yes
    labels:
      traefik.backend: "grafana"
      traefik.frontend.rule: "Host:grafana.stats"
      traefik.port: "3000"
      traefik.docker.network: "traefik"
      traefik.enable: "true"
    restart_policy: unless-stopped
    state: started
  tags: grafana
