---
- name: librenms-db - start
  docker_container:
    name: librenms-db
    image: "{{ librenms_db_image }}"
    pull: yes
    env:
      MYSQL_ROOT_PASSWORD: "{{ librenms_db_root_pass }}"
      MYSQL_DATABASE: "{{ librenms_db_user }}"
      MYSQL_USER: "{{ librenms_db_user }}"
      MYSQL_PASSWORD: "{{ librenms_db_pass }}"
      MYSQL_CHARSET: "utf8mb4"
      MYSQL_COLLATION: "utf8mb4_unicode_ci"
    volumes:
      - "{{ app_path }}/librenms/db:/var/lib/mysql"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: yes
    command:
      --sql-mode=""
      --lower_case_table_names=0
    restart_policy: unless-stopped
    state: started
  no_log: true
  tags: librenms

- name: librenms - create dir
  file:
    path: "{{ app_path }}/librenms"
    state: directory
    recurse: yes
  tags: librenms

- name: librenms - copy files
  template:
    src: templates/config.custom.php.j2
    dest: "{{ app_path }}/librenms/config.custom.php"
    owner: "999"
    group: "999"
    mode: 0664
  notify: librenms - restart
  tags: librenms

- name: librenms - start
  docker_container:
    name: librenms
    image: "{{ librenms_image }}"
    pull: yes
    env:
      TZ: "{{ tz }}"
      DB_HOST: "librenms-db"
      DB_NAME: "{{ librenms_db_user }}"
      DB_USER: "{{ librenms_db_user }}"
      DB_PASS: "{{ librenms_db_pass }}"
      APP_KEY: "{{ librenms_app_key }}"
      BASE_URL: "{{ librenms_base_url }}"
    volumes:
      - "{{ app_path }}/librenms/logs/nginx:/var/log/nginx"
      - "{{ app_path }}/librenms/logs/app:/opt/librenms/logs"
      - "{{ app_path }}/librenms/rrd:/opt/librenms/rrd"
      - "{{ app_path }}/librenms/config.custom.php:/opt/librenms/conf.d/config.custom.php"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: yes
    labels:
      traefik.enable: "true"
      traefik.http.routers.librenms.rule: "HostRegexp(`nms{fqdn:(.{{ app_base_domain }})?}`)"
      traefik.http.routers.librenms.entrypoints: "websecure"
      traefik.http.routers.librenms.tls: "true"
    restart_policy: unless-stopped
    state: started
  register: librenms_start
  notify: librenms - setup_database
  no_log: true
  tags: librenms

- name: librenms - customize
  command: docker exec librenms sh -c '{{ item }}'
  changed_when: true
  when: librenms_start.changed
  notify: librenms - restart
  loop:
    - echo "TLS_REQCERT allow" >> /etc/ldap/ldap.conf
  tags: librenms
