---
- name: loki
  ansible.builtin.include_tasks: loki.yml
  tags: [loki, grafana]

- name: prometheus
  ansible.builtin.include_tasks: prometheus.yml
  tags: [prometheus, grafana]

- name: influxdb
  ansible.builtin.include_tasks: influxdb.yml
  tags: [influxdb, grafana]

- name: grafana
  ansible.builtin.include_tasks: grafana.yml
  tags: grafana

- name: librenms
  ansible.builtin.include_tasks: librenms.yml
  tags: librenms

- name: mosquitto
  ansible.builtin.include_tasks: mosquitto.yml
  tags: mosquitto

- name: grafana - configure freeipa
  ansible.builtin.include_tasks: ../mgmt/tasks/freeipa_service_bind.yml
  vars:
    freeipa_service_bind_sysaccount_dn: "{{ grafana_ldap_bind_dn }}"
    freeipa_service_bind_sysaccount_pass: "{{ grafana_ldap_bind_pw }}"
    freeipa_service_bind_group_name: "{{ item }}"
  args:
    apply:
      tags: grafana
  loop:
    - "{{ grafana_ldap_access_group }}"
    - "{{ grafana_ldap_admins }}"
    - "{{ grafana_ldap_editors }}"
    - "{{ grafana_ldap_viewers }}"
  tags: grafana

- name: librenms - configure freeipa
  ansible.builtin.include_tasks: ../mgmt/tasks/freeipa_service_bind.yml
  vars:
    freeipa_service_bind_sysaccount_dn: "{{ librenms_ldap_bind_dn }}"
    freeipa_service_bind_sysaccount_pass: "{{ librenms_ldap_bind_pw }}"
    freeipa_service_bind_group_name: "{{ item }}"
  args:
    apply:
      tags: librenms
  loop:
    - "{{ librenms_ldap_admins }}"
    - "{{ librenms_ldap_admins_ro }}"
    - "{{ librenms_ldap_users }}"
  tags: librenms
