---
- name: restart wireguard
  service:
    name: wg-quick@wg0
    enabled: yes
    state: restarted

- name: save iptables
  command: /usr/sbin/netfilter-persistent save

- name: restart iptables
  service:
    name: netfilter-persistent
    state: restarted
  listen: save iptables

- name: execute antifilter
  command: "{{ antifilter_path }}"
  listen: restart bird

- name: restart bird
  service:
    name: bird
    state: restarted
