---
- name: restart wireguard
  ansible.builtin.service:
    name: wg-quick@{{ vps_wg_interface }}
    enabled: yes
    state: restarted

- name: save iptables
  ansible.builtin.command: /usr/sbin/netfilter-persistent save

- name: restart iptables
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted
  listen: save iptables

- name: execute antifilter
  ansible.builtin.command: "{{ vps_antifilter_path }}"
  listen: restart bird

- name: restart bird
  ansible.builtin.service:
    name: bird
    state: restarted

- name: restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
