---
- name: Install packages
  package:
    state: present
    name:
      - libpve-apiclient-perl
      - sudo

- name: Create dir
  file:
    path: "{{ snmp_extend_scripts_path }}"
    state: directory
    mode: 0755

- name: Download scripts
  get_url:
    url: "{{ item }}"
    dest: "{{ snmp_extend_scripts_path }}/{{ item | basename }}"
    force: yes
  loop: "{{ snmp_extend_scripts }}"
  notify: restart snmpd

- name: Copy smart.config
  template:
    src: templates/smart.config.j2
    dest: /etc/snmp/extend/smart.config
    mode: 0644
  notify: restart snmpd

- name: Copy sudoers.d file
  copy:
    src: files/snmp_sudo
    dest: /etc/sudoers.d
    mode: 0440

- name: Create a cron job
  cron:
    name: snmp_smart
    minute: "*/5"
    user: root
    job: "/etc/snmp/extend/smart -u"
    cron_file: snmp_smart

- name: Update snmpd.conf
  blockinfile:
    path: /etc/snmp/snmpd.conf
    block: |
      extend hardware '/bin/cat /sys/devices/virtual/dmi/id/product_name'
      extend manufacturer '/bin/cat /sys/devices/virtual/dmi/id/sys_vendor'
      extend serial '/usr/bin/sudo /bin/cat /sys/devices/virtual/dmi/id/product_serial'
      extend distro /etc/snmp/extend/distro
      extend proxmox /usr/bin/sudo /etc/snmp/extend/proxmox
      extend smart /etc/snmp/extend/smart
      {% if inventory_hostname == "spsrv" %}
      extend ups-nut /etc/snmp/extend/ups-nut.sh homelabups
      {% endif %}
  notify: restart snmpd
