---
- name: Docker
  include_role:
    name: geerlingguy.docker

- name: Create docker.service.d directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    recurse: yes

- name: Copy daemon.json
  copy:
    src: files/daemon.json
    dest: /etc/docker
    mode: 0644
  notify: Restart docker service

- name: Force all notified handlers
  meta: flush_handlers
