---
- name: Load br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Set sysctl entries
  sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_set: yes
    reload: yes
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
