---
- name: delugevpn - create dir
  file:
    path: "{{ app_path }}/delugevpn/config/openvpn"
    state: directory
    recurse: yes
  tags: delugevpn

- name: delugevpn - copy files
  copy:
    src: files/pia-czech.ovpn
    dest: "{{ app_path }}/delugevpn/config/openvpn"
  tags: delugevpn

- name: delugevpn - start
  docker_container:
    name: delugevpn
    image: "{{ delugevpn_image }}"
    pull: yes
    ports:
      - "8112:8112"
      - "8118:8118"
      - "58846:58846"
      - "58946:58946"
    env:
      VPN_ENABLED: "yes"
      VPN_USER: "{{ delugevpn_vpn_user }}"
      VPN_PASS: "{{ delugevpn_vpn_pass }}"
      VPN_PROV: "pia"
      STRICT_PORT_FORWARD: "yes"
      ENABLE_PRIVOXY: "yes"
      LAN_NETWORK: "192.168.10.0/24,10.1.100.0/24"
      NAME_SERVERS: "209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1"
      DELUGE_DAEMON_LOG_LEVEL: "warning"
      DELUGE_WEB_LOG_LEVEL: "warning"
      ADDITIONAL_PORTS: "1234"
      DEBUG: "false"
      UMASK: "022"
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "delugevpn-data:/data"
      - "{{ app_path }}/delugevpn/config:/config"
      - "{{ app_path }}/data/downloads:/downloads"
    capabilities:
      - net_admin
    restart_policy: unless-stopped
    state: started
  no_log: true
  tags: delugevpn
