---
- name: jackett - create dir
  file:
    path: "{{ app_path }}/jackett"
    state: directory
    recurse: yes
  tags: jackett

- name: jackett - copy files
  copy:
    src: files/Definitions
    dest: "{{ app_path }}/jackett"
  tags: jackett

- name: jackett - start
  docker_container:
    name: jackett
    image: linuxserver/jackett:latest
    pull: yes
    ports:
      - "9117:9117"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/jackett/config:/config"
      - "{{ app_path }}/data/downloads:/downloads"
      - "{{ app_path }}/jackett/Definitions/bitru.yml:/app/Jackett/Definitions/bitru.yml:ro"
      - "{{ app_path }}/jackett/Definitions/eniahd.yml:/app/Jackett/Definitions/eniahd.yml:ro"
      - "{{ app_path }}/jackett/Definitions/kinozal.yml:/app/Jackett/Definitions/kinozal.yml:ro"
      - "{{ app_path }}/jackett/Definitions/riperam.yml:/app/Jackett/Definitions/riperam.yml:ro"
      - "{{ app_path }}/jackett/Definitions/vanila.yml:/app/Jackett/Definitions/vanila.yml:ro"
    restart_policy: unless-stopped
    state: started
  tags: jackett
