---
# - name: muximux
#   ansible.builtin.include_tasks: muximux.yml
#   tags: muximux

# - name: delugevpn
#   ansible.builtin.include_tasks: delugevpn.yml
#   tags: delugevpn

# - name: jackett
#   ansible.builtin.include_tasks: jackett.yml
#   tags: jackett

# - name: prowlarr
#   ansible.builtin.include_tasks: prowlarr.yml
#   tags: prowlarr

# - name: sonarr
#   ansible.builtin.include_tasks: sonarr.yml
#   tags: sonarr

# - name: radarr
#   ansible.builtin.include_tasks: radarr.yml
#   tags: radarr

# - name: lidarr
#   ansible.builtin.include_tasks: lidarr.yml
#   tags: lidarr

# - name: bazarr
#   ansible.builtin.include_tasks: bazarr.yml
#   tags: bazarr

# - name: flaresolverr
#   ansible.builtin.include_tasks: flaresolverr.yml
#   tags: flaresolverr

# - name: monitorrent
#   ansible.builtin.include_tasks: monitorrent.yml
#   tags: monitorrent

- name: samba
  ansible.builtin.include_tasks: samba.yml
  tags: samba

- name: minio
  ansible.builtin.include_tasks: minio.yml
  tags: minio

# - name: nextcloud
#   ansible.builtin.include_tasks: nextcloud.yml
#   tags: nextcloud

- name: nextcloud - configure freeipa
  ansible.builtin.include_tasks: ../mgmt/tasks/freeipa_service_bind.yml
  vars:
    freeipa_service_bind_sysaccount_dn: "{{ nextcloud_ldap_bind_dn }}"
    freeipa_service_bind_sysaccount_pass: "{{ nextcloud_ldap_bind_pw }}"
    freeipa_service_bind_group_name: "{{ nextcloud_ldap_access_group }}"
  args:
    apply:
      tags: nextcloud
  tags: nextcloud

- name: minio - consul_catalog
  ansible.builtin.include_tasks: ../../consul_catalog/tasks/main.yml
  vars:
    consul_service_name: minio
    consul_service_address: s3.{{ app_base_domain }}
    consul_service_metrics_path: /minio/v2/metrics/cluster
  args:
    apply:
      tags: jenkins
  tags: jenkins
