---
- name: muximux - start
  docker_container:
    name: muximux
    image: "{{ muximux_image }}"
    pull: yes
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/muximux/config:/config"
    networks:
      - name: "{{ app_network_name }}"
    networks_cli_compatible: yes
    labels:
      traefik.enable: "true"
      traefik.http.routers.muximux.rule: "HostRegexp(`spnas{fqdn:(.home.devmem.ru)?}`)"
      traefik.http.routers.muximux.entrypoints: "websecure"
      traefik.http.routers.muximux.tls: "true"
    restart_policy: unless-stopped
    state: started
  tags: muximux

- name: muximux - copy files
  copy:
    src: files/settings.ini.php
    dest: "{{ app_path }}/muximux/config/www/muximux"
    force: no
  tags: muximux
