---
- name: nextcloud-db - start
  docker_container:
    name: nextcloud-db
    image: "{{ nextcloud_db_image }}"
    pull: yes
    env:
      MYSQL_ROOT_PASSWORD: "{{ nextcloud_db_root_pass }}"
      MYSQL_DATABASE: "{{ nextcloud_db_user }}"
      MYSQL_USER: "{{ nextcloud_db_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_db_pass }}"
      MYSQL_CHARSET: "utf8mb4"
      MYSQL_COLLATION: "utf8mb4_unicode_ci"
    volumes:
      - "{{ app_path }}/nextcloud/db:/var/lib/mysql"
    restart_policy: unless-stopped
    state: started
  no_log: true
  tags: nextcloud

- name: nextcloud - start
  docker_container:
    name: nextcloud
    image: "{{ nextcloud_image }}"
    pull: yes
    ports:
      - "8888:8888"
    env:
      UID: "{{ puid }}"
      GID: "{{ pgid }}"
      TZ: "{{ tz }}"
      DB_TYPE: "mysql"
      DB_HOST: "nextcloud-db"
      DB_NAME: "{{ nextcloud_db_user }}"
      DB_USER: "{{ nextcloud_db_user }}"
      DB_PASSWORD: "{{ nextcloud_db_pass }}"
      ADMIN_USER: "admin"
      ADMIN_PASSWORD: "admin"
    volumes:
      - "{{ app_path }}/data/cloud/nextcloud:/data"
      - "{{ app_path }}/nextcloud/config:/nextcloud/config"
      - "{{ app_path }}/nextcloud/apps:/nextcloud/apps2"
      - "nextcloud-themes:/nextcloud/themes"
    links:
      - "nextcloud-db:nextcloud-db"
    restart_policy: unless-stopped
    state: started
  register: nextcloud_start
  no_log: true
  tags: nextcloud

- block:
    - name: nextcloud - wait for container startup is complete
      uri:
        url: "https://cloud.devmem.ru"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 120
      delay: 10
      tags: nextcloud

    - name: nextcloud - fix ldap
      command: docker exec --user root nextcloud sh -c '{{ item }}'
      notify: nextcloud - restart
      loop:
        - echo "TLS_REQCERT allow" >> /etc/openldap/ldap.conf
      tags: nextcloud

    - name: nextcloud - execute commands in container
      command: docker exec nextcloud sh -c '{{ item }}'
      notify: nextcloud - restart
      loop:
        - occ db:add-missing-columns
        - occ db:add-missing-primary-keys
        - occ db:add-missing-indices
      tags: nextcloud
  when: nextcloud_start.changed
