---
- name: radarr - start
  docker_container:
    name: radarr
    image: "{{ radarr_image }}"
    pull: yes
    ports:
      - "7878:7878"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/radarr/config:/config"
      - "{{ app_path }}/data/downloads:/downloads"
    restart_policy: unless-stopped
    state: started
  tags: radarr
