---
- name: sonarr - start
  docker_container:
    name: sonarr
    image: "{{ sonarr_image }}"
    pull: yes
    ports:
      - "8989:8989"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/sonarr/config:/config"
      - "{{ app_path }}/data/downloads:/downloads"
    restart_policy: unless-stopped
    state: started
  tags: sonarr
