---
- name: Copy files
  ansible.builtin.copy:
    src: files/{{ item.src }}
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: kvm.conf, dest: /etc/modprobe.d }
    - { src: kvm-intel.conf, dest: /etc/modprobe.d }
    - { src: modules, dest: /etc }

- name: Edit grub config
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet delayacct intel_iommu=on"'
  notify: update-grub
