---
- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - postfix
      - postfix-pcre
      - libsasl2-modules

- name: Copy files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: /etc/postfix/{{ item.dest }}
    mode: "{{ item.mode }}"
  loop:
    - { src: sasl_passwd.j2, dest: sasl_passwd, mode: 600 }
    - { src: smtp_header_checks.j2, dest: smtp_header_checks, mode: 644 }
    - { src: main.cf.j2, dest: main.cf, mode: 644 }
    - { src: smtp_generic_maps.j2, dest: smtp_generic_maps, mode: 644 }
  notify: postfix config changed
