---
- name: Install packages
  apt:
    state: present
    name:
      - postfix
      - postfix-pcre
      - libsasl2-modules

- name: Copy auth info
  template:
    src: templates/sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: 0600
  notify: postmap

- name: Copy replacement rules
  template:
    src: templates/smtp_header_checks.j2
    dest: /etc/postfix/smtp_header_checks
    mode: 0644
  notify: postfix config changed

- name: Copy main.cf
  template:
    src: templates/main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
  notify: postfix config changed
