---
- name: jackett - restart
  community.docker.docker_container:
    name: jackett
    state: started
    restart: true
  when: not jackett_start.changed

- name: samba - restart
  community.docker.docker_container:
    name: samba
    state: started
    restart: true
  no_log: true
  when: not samba_start.changed

- name: nextcloud - restart
  community.docker.docker_container:
    name: nextcloud
    state: started
    restart: true
  no_log: true

- name: muximux - restart
  community.docker.docker_container:
    name: muximux
    state: started
    restart: true
