---
portainer_api_url: https://portainer.{{ inventory__homelab_domain }}/api
portainer_api_user: ansible
portainer_api_pass: "{{ inventory__ldap_users[portainer_api_user].password }}"

hostname: mgmt
net_ip: 127.0.0.1
portainer_api_hostname: "{{ hostname }}"
portainer_api_endpoint_url: tcp://{{ net_ip }}:2375
portainer_api_endpoint_public_url: "{{ net_ip }}"
