---
- name: homeassistant
  ansible.builtin.include_tasks: homeassistant.yml
  tags: homeassistant

- name: esphome
  ansible.builtin.include_tasks: esphome.yml
  tags: esphome

- name: grocy
  ansible.builtin.include_tasks: grocy.yml
  tags: grocy
