---
- name: storage tasks
  block:
    - name: mount
      ansible.builtin.include_tasks: mount.yml

    - name: mergerfs
      ansible.builtin.include_tasks: mergerfs.yml

    - name: snapraid
      ansible.builtin.include_tasks: snapraid.yml

    - name: nfs
      ansible.builtin.include_tasks: nfs.yml
  when: inventory_hostname == "spsrv"
