---
- include_tasks: util_pool_list.yml
- include_tasks: util_vm_list.yml

- name: Destroy VM
  vars:
    vm_id: "{{ vm_id_tpl }}{{ item }}"
    vmid_string: "vmid: {{ vm_id }}"
  shell: >
    qm stop {{ vm_id }} && qm destroy {{ vm_id }}
  loop: "{{ vm_index_list }}"
  when: vmid_string in vm_list.stdout

- name: Delete Resource Pool
  command: >
    pvesh delete /pools/{{ resourse_pool }}
  ignore_errors: yes
  when: resourse_pool in pool_list.stdout
