---
- include_tasks: util_vm_status.yml

- block:
  - name: Start VM
    vars:
      vmid: "{{ vmid_tpl }}{{ item }}"
      vmid_string: "vmid: {{ vmid }}"
    command: >
      qm start {{ vmid }}
    loop: "{{ vm_index_list }}"
    when: >
      resource_type == "vm" and
      'running' not in vm_status.results[item].stdout

  - name: Start CT
    vars:
      vmid: "{{ vmid_tpl }}{{ item }}"
      vmid_string: "vmid: {{ vmid }}"
    command: >
      pct start {{ vmid }}
    loop: "{{ vm_index_list }}"
    when: >
      resource_type == "ct" and
      'running' not in ct_status.results[item].stdout

  - name: Wait for SSH port become available
    vars:
      vmid: "{{ vmid_tpl }}{{ item }}"
      vmid_string: "vmid: {{ vmid }}"
    wait_for:
      host: "{{ net_ip_tpl }}{{ item }}"
      port: 22
    loop: "{{ vm_index_list }}"
  when: vmid_string in vm_list.stdout
