---
- include_tasks: util_vm_status.yml

- block:
  - name: Shutdown VM
    vars:
      vmid: "{{ vmid_tpl }}{{ item }}"
      vmid_string: "vmid: {{ vmid }}"
    shell: >
      qm shutdown {{ vmid }} && qm wait {{ vmid }} -timeout 60
    loop: "{{ vm_index_list }}"
    when: >
      resource_type == "vm" and
      'stopped' not in vm_status.results[item].stdout

  - name: Shutdown CT
    vars:
      vmid: "{{ vmid_tpl }}{{ item }}"
      vmid_string: "vmid: {{ vmid }}"
    shell: >
      pct shutdown {{ vmid }}
    loop: "{{ vm_index_list }}"
    when: >
      resource_type == "ct" and
      'stopped' not in ct_status.results[item].stdout
  when: vmid_string in vm_list.stdout
