---
- include_tasks: util_vm_list.yml

- name: Get VM status
  vars:
    vm_id: "{{ vm_id_tpl }}{{ item }}"
    vmid_string: "vmid: {{ vm_id }}"
  shell: >
    qm status {{ vm_id }}
  register: vm_status
  loop: "{{ vm_index_list }}"
  changed_when: false
  when: vmid_string in vm_list.stdout
