---
- name: traefik - create network
  docker_network:
    name: "{{ traefik_network_name }}"
  tags: traefik

- name: traefik - load certificate vars
  include_vars: vars/cert.vault.yml
  tags: traefik

- name: traefik - create dir
  file:
    path: "{{ traefik_cert_path_host }}"
    state: directory
    recurse: yes
  tags: traefik

- name: traefik - copy certificate
  copy:
    content: "{{ ssl_certificate }}"
    dest: "{{ traefik_cert_path_host }}/{{ traefik_cert_name }}.crt"
  notify: traefik - restart
  tags: traefik

- name: traefik - copy certificate private key
  copy:
    content: "{{ ssl_private_key }}"
    dest: "{{ traefik_cert_path_host }}/{{ traefik_cert_name }}.key"
  notify: traefik - restart
  no_log: true
  tags: traefik

- name: traefik - copy config
  template:
    src: templates/dyn.toml.j2
    dest: "{{ traefik_config_file_host }}"
  notify: traefik - restart
  tags: traefik

- name: traefik - start
  docker_container:
    name: traefik
    image: "{{ traefik_image }}"
    pull: yes
    ports:
      - "{{ traefik_web_port }}:80"
      - "{{ traefik_websecure_port }}:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ traefik_config_file_host }}:{{ traefik_config_file }}"
      - "{{ traefik_cert_path_host }}:{{ traefik_cert_path }}"
    networks:
      - name: "{{ traefik_network_name }}"
    networks_cli_compatible: yes
    command: >
      --log.level={{ traefik_log_level }}
      --api=true
      --providers.file.filename={{ traefik_config_file }}
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entrypoints.web.address=:{{ traefik_web_port }}
      --entrypoints.web.http.redirections.entryPoint.to=websecure
      --entrypoints.web.http.redirections.entryPoint.scheme=https
      --entrypoints.websecure.address=:{{ traefik_websecure_port }}
      --serverstransport.insecureskipverify=true
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "{{ traefik_hostname_rule }}"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.tls: "true"
    restart_policy: unless-stopped
    state: started
  register: traefik_start
  tags: traefik
