---
- name: airvideohd - start
  community.docker.docker_container:
    name: airvideohd
    image: "{{ airvideohd_image }}"
    pull: true
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/shm/airvideohd:/conversionPath"
      - "{{ app_path }}/airvideohd/config:/config"
      - "{{ app_path }}/downloads/Video:/videos"
    network_mode: host
    restart_policy: unless-stopped
    state: started
  tags: airvideohd
