---
- name: plex - run
  docker_container:
    name: plex
    image: linuxserver/plex:latest
    pull: yes
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      VERSION: "latest"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/shm:/ram_transcode"
      - "{{ app_path }}/plex/config:/config"
      - "{{ app_path }}/downloads:/storage/downloads"
    network_mode: host
    restart_policy: unless-stopped
    state: started

- name: tautulli - run
  docker_container:
    name: tautulli
    image: linuxserver/tautulli:latest
    pull: yes
    ports:
      - "8181:8181"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/tautulli/config:/config"
      - "{{ app_path }}/plex/config/Library/Application Support/Plex Media Server/Logs:/logs"
    restart_policy: unless-stopped
    state: started

- name: ombi - run
  docker_container:
    name: ombi
    image: linuxserver/ombi:latest
    pull: yes
    ports:
      - "3579:3579"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/ombi/config:/config"
    restart_policy: unless-stopped
    state: started