---
- name: tautulli - start
  docker_container:
    name: tautulli
    image: linuxserver/tautulli:latest
    pull: yes
    ports:
      - "8181:8181"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ tz }}"
    volumes:
      - "{{ app_path }}/tautulli/config:/config"
      - "{{ app_path }}/plex/config/Library/Application Support/Plex Media Server/Logs:/logs"
    restart_policy: unless-stopped
    state: started
  tags: tautulli
