---
- name: Update postfix lookup tables
  ansible.builtin.command: >
    postmap /etc/postfix/{{ item }}
  loop:
    - sasl_passwd
    - smtp_generic_maps
  listen: postfix config changed

- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted
  listen: postfix config changed

- name: Send test mail
  ansible.builtin.shell: >
    echo "test mail from {{ inventory_hostname }}" | /usr/bin/pvemailforward
  changed_when: false
  listen: postfix config changed
