---
- name: Update postfix lookup tables
  command: postmap /etc/postfix/{{ item }}
  loop:
    - sasl_passwd
    - smtp_generic_maps
  listen: postfix config changed

- name: Restart postfix
  service:
    state: restarted
    name: postfix
  listen: postfix config changed

- name: Send test mail
  shell: echo "test mail from {{ inventory_hostname }}" | /usr/bin/pvemailforward
  changed_when: false
  listen: postfix config changed
