---
- name: Configure APT sources
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: sources.list.j2, dest: /etc/apt/sources.list }
    - { src: pve-no-subscription.list.j2, dest: /etc/apt/sources.list.d/pve-no-subscription.list }

- name: Remove PVE Enterprise repo
  file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Upgrade packages
  package:
    update_cache: yes
    state: latest
    name: '*'

- name: Install packages
  package:
    state: present
    name:
      - openvswitch-switch
      - patch
      - pve-headers
