---
- name: Configure no-subscription repo
  ansible.builtin.template:
    src: pve-no-subscription.list.j2
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    mode: 0644

- name: Remove enterprise repo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Update APT cache
  ansible.builtin.package:
    update_cache: yes

- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - openvswitch-switch
      - patch
      - pve-headers
