---
- name: gitea - restart
  community.docker.docker_container:
    name: gitea
    state: started
    restart: true
  when: not gitea_start.changed

- name: registry - restart
  community.docker.docker_container:
    name: registry
    state: started
    restart: true
  when: not registry_start.changed

- name: jenkins - restart
  community.docker.docker_container:
    name: jenkins
    state: started
    restart: true
  when: not jenkins_start.changed

- name: nexus - restart
  community.docker.docker_container:
    name: nexus
    state: started
    restart: true
  no_log: true

- name: nexus - wait for api become available
  ansible.builtin.uri:
    url: "{{ nexus_api_url }}/status"
    status_code: 200
  register: __nexus_wait_for_api
  until: __nexus_wait_for_api.status == 200
  retries: 60
  delay: 1
  listen: nexus - restart
