---
packages_base:
  - bmon
  - bzip2
  - curl
  - git
  - htop
  - iftop
  - iotop
  - jq
  - mc
  - mtr-tiny
  - ncdu
  - net-tools
  - nfs-common
  - open-iscsi
  - pigz
  - rsync
  - sysstat
  - tcpdump
  - tmux
  - unzip
  - wget
  - zip
  - zstd
