---
- name: gitea-db - start
  docker_container:
    name: gitea-db
    image: "{{ gitea_db_image }}"
    pull: yes
    env:
      MYSQL_ROOT_PASSWORD: "{{ gitea_db_root_pass }}"
      MYSQL_DATABASE: "{{ gitea_db_user }}"
      MYSQL_USER: "{{ gitea_db_user }}"
      MYSQL_PASSWORD: "{{ gitea_db_pass }}"
      MYSQL_CHARSET: "utf8mb4"
      MYSQL_COLLATION: "utf8mb4_unicode_ci"
    volumes:
      - "{{ app_path }}/gitea/db:/var/lib/mysql"
    restart_policy: unless-stopped
    state: started
  no_log: true
  tags: gitea

- name: gitea - create dir
  file:
    path: "{{ app_path }}/gitea/data/gitea/conf"
    state: directory
    recurse: yes
  tags: gitea

- name: gitea - copy files
  template:
    src: templates/{{ item.src }}
    dest: "{{ app_path }}/{{ item.dest }}"
  loop:
    - {src: app.ini.j2, dest: gitea/data/gitea/conf/app.ini}
  notify: gitea - restart
  tags: gitea

- name: gitea - start
  docker_container:
    name: gitea
    image: "{{ gitea_image }}"
    pull: yes
    ports:
      - "3000:3000"
      - "127.0.0.1:2222:22"
    env:
      USER_UID: "{{ puid }}"
      USER_GID: "{{ pgid }}"
      DB_TYPE: "mysql"
      DB_HOST: "{{ gitea_db_host }}"
      DB_NAME: "{{ gitea_db_user }}"
      DB_USER: "{{ gitea_db_user }}"
      DB_PASSWD: "{{ gitea_db_pass }}"
      APP_NAME: "Gitea"
      RUN_MODE: "prod"
      DOMAIN: "{{ gitea_domain }}"
      SSH_DOMAIN: "{{ gitea_domain }}"
      ROOT_URL: "{{ gitea_root_url }}/"
      LFS_START_SERVER: "true"
      DISABLE_REGISTRATION: "true"
      REQUIRE_SIGNIN_VIEW: "true"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "{{ app_path }}/gitea/data:/data"
    links:
      - "gitea-db:gitea-db"
    restart_policy: unless-stopped
    state: started
  register: gitea_start
  no_log: true
  tags: gitea

- name: gitea - ssh passthrough - create dir
  file:
    path: /app/gitea
    state: directory
    recurse: yes
  tags: gitea

- name: gitea - ssh passthrough - copy files
  copy:
    src: files/gitea
    dest: /app/gitea
    mode: 0755
  tags: gitea

- name: gitea - ssh passthrough - create group
  group:
    name: git
    gid: "{{ pgid }}"
  tags: gitea

- name: gitea - ssh passthrough - create user
  user:
    name: git
    uid: "{{ puid }}"
    group: git
    generate_ssh_key: yes
    password: ""
    update_password: on_create
  tags: gitea

- name: gitea - ssh passthrough - create authorized_keys symlink
  file:
    src: "{{ app_path }}/gitea/data/git/.ssh/authorized_keys"
    dest: "/home/git/.ssh/authorized_keys"
    state: link
    owner: git
    group: git
    force: yes
    follow: no
  tags: gitea

- name: gitea - ssh passthrough - get id_rsa.pub content
  command: cat "/home/git/.ssh/id_rsa.pub"
  register: git_key
  changed_when: no
  tags: gitea

- name: gitea - ssh passthrough - add ssh key
  lineinfile:
    path: "{{ app_path }}/gitea/data/git/.ssh/authorized_keys"
    line: no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty {{ git_key.stdout }}
    owner: git
    group: git
    create: yes
    state: present
  tags: gitea

- name: gitea - gpg - check if key already exists
  command: docker exec -u git gitea sh -c 'gpg --list-secret-keys | grep "gitea"'
  register: gpg_key
  changed_when: false
  failed_when: gpg_key.rc == 2
  tags: gitea

- block:
    - name: gitea - gpg - copy key template
      copy:
        src: files/gen-key-script
        dest: "{{ app_path }}/gitea/data/git/.gnupg"
        owner: git
        group: git
        mode: 0600
      tags: gitea

    - name: gitea - gpg - generate key
      command: docker exec -u git gitea sh -c 'gpg --batch --gen-key /data/git/.gnupg/gen-key-script'
      tags: gitea

    - name: gitea - gpg - delete key template
      file:
        path: "{{ app_path }}/gitea/data/git/.gnupg/gen-key-script"
        state: absent
      tags: gitea

    - name: gitea - gpg - get key id
      command: docker exec -u git gitea sh -c 'gpg -k --keyid-format SHORT | grep "pub" | awk "{printf \$2}" | awk -F/ "{printf \$2}"'
      register: gpg_key_id
      changed_when: false
      tags: gitea

    - name: gitea - gpg - configure git signing
      command: docker exec -u git gitea sh -c '{{ item }}'
      loop:
        - git config --global user.signingkey {{ gpg_key_id.stdout }}
        - git config --global commit.gpgsign true
      notify: gitea - restart
      tags: gitea
  when: gpg_key is defined and not gpg_key.stdout
