---
- name: gitea
  ansible.builtin.include_tasks: gitea.yml
  tags: gitea

- name: jenkins
  ansible.builtin.include_tasks: jenkins.yml
  tags: jenkins

- name: nexus
  ansible.builtin.include_tasks: nexus.yml
  tags: nexus

# - name: drone
#   ansible.builtin.include_tasks: drone.yml
#   tags: drone

# - name: registry
#   ansible.builtin.include_tasks: registry.yml
#   tags: registry

# - name: code
#   ansible.builtin.include_tasks: code.yml
#   tags: code

- name: gitea - configure freeipa
  ansible.builtin.include_tasks: ../mgmt/tasks/freeipa_service_bind.yml
  vars:
    freeipa_service_bind_sysaccount_dn: "{{ gitea_ldap_bind_dn }}"
    freeipa_service_bind_sysaccount_pass: "{{ gitea_ldap_bind_pw }}"
    freeipa_service_bind_group_name: "{{ item }}"
  args:
    apply:
      tags: gitea
  loop:
    - "{{ gitea_ldap_access_group }}"
    - "{{ gitea_ldap_admins }}"
  tags: gitea

- name: jenkins - configure freeipa
  ansible.builtin.include_tasks: ../mgmt/tasks/freeipa_service_bind.yml
  vars:
    freeipa_service_bind_sysaccount_dn: "{{ jenkins_ldap_bind_dn }}"
    freeipa_service_bind_sysaccount_pass: "{{ jenkins_ldap_bind_pw }}"
    freeipa_service_bind_group_name: "{{ jenkins_ldap_access_group }}"
  args:
    apply:
      tags: jenkins
  tags: jenkins
