---
- name: goaccess - start
  docker_container:
    name: goaccess
    image: "{{ goaccess_image }}"
    pull: yes
    ports:
      - "7880:7880"
    env:
      PUID: "0"
      PGID: "0"
      TZ: "{{ inventory__docker_tz }}"
      SKIP_ARCHIVED_LOGS: "False"
    volumes:
      - "{{ app_path }}/npm/app/data/logs:/opt/log"
    restart_policy: unless-stopped
    state: absent
  tags: goaccess
