---
app_path: /docker/mail

mailserver_version: 10.1.2

mail_image: mailserver/docker-mailserver:{{ mailserver_version }}
mail_autodiscover_image: monogramm/autodiscover-email-settings:latest

mail_hostname: mail
mail_domainname: devmem.ru

mail_cert_name: cert
mail_cert_path: /tmp/certs
mail_cert_path_host: "{{ app_path }}/certs"
mail_config_path_host: "{{ app_path }}/config"

mail_ldap_starttls: "yes"
mail_ldap_server_host: ipa.home.devmem.ru
mail_ldap_search_base: dc=home,dc=devmem,dc=ru
mail_ldap_bind_dn: uid=mailsvc,cn=sysaccounts,cn=etc,{{ mail_ldap_search_base }}
mail_ldap_bind_pw: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38303832646430653739333239333133333132626636393938373435373836363536353963656239
          6138376235316238353034613631306434356333386263650a323766366135663633383464396435
          31303561336233306565393265343065623561613439666465303935363131383039303830396164
          3265656133636464370a613134306533356130326333653134623765663035333438626561306162
          3163

mail_ldap_access_group: mail_users
mail_ldap_access_filter: (objectclass=inetorgperson)(memberof=cn={{ mail_ldap_access_group }},cn=groups,cn=accounts,{{ mail_ldap_search_base }})

mail_ldap_query_filter_user: (&{{ mail_ldap_access_filter }}(mail=%s))
mail_ldap_query_filter_group: (&{{ mail_ldap_access_filter }}(mailgroupmember=%s))
mail_ldap_query_filter_alias: (&{{ mail_ldap_access_filter }}(|(mail=%s)(mailalias=%s)))
mail_ldap_query_filter_domain: (&{{ mail_ldap_access_filter }}(|(mail=*@%s)(mailalias=*@%s)(mailgroupmember=*@%s)))

mail_dovecot_pass_filter: (&{{ mail_ldap_access_filter }}(uid=%n))
mail_dovecot_user_filter: (&{{ mail_ldap_access_filter }}(uid=%n))
mail_dovecot_pass_attrs: uid=user,userPassword=password
mail_dovecot_user_attrs: =home=/var/mail/{{ mail_domainname }}/%n,=uid=5000,=gid=5000,=mail=maildir:/var/mail/{{ mail_domainname }}/%n

mail_saslauthd_ldap_filter: (&{{ mail_ldap_access_filter }}(uid=%u))
