---
- block:
    - name: Create VM
      vars:
        vmid_string: "vmid: {{ vmid }}"
      command: >
        qm create {{ vmid }}
          --pool {{ resourse_pool }}
          --ostype {{ vm_ostype }}
          --name {{ hostname }}
          --description "{{ comment }}"
          --agent 1,fstrim_cloned_disks=1
          --cores {{ cores }}
          --memory {{ mem }}
          --net0 virtio,bridge={{ net_br }},tag={{ net_vlan }}
          --ipconfig0 gw={{ net_gw }},ip={{ net_ip }}/{{ net_cidr }}
          --nameserver {{ net_dns }}
          --searchdomain {{ net_domain }}
          --sshkeys "{{ ssh_keys }}"

    - name: Set VM default user password
      vars:
        vmid_string: "vmid: {{ vmid }}"
      command: >
        qm set {{ vmid }}
          --cipassword {{ user_pass }}
      no_log: true

    - name: Import qcow2 image as VM disk
      vars:
        vmid_string: "vmid: {{ vmid }}"
      command: >
        qm importdisk {{ vmid }} {{ vm_image }} {{ disk_storage }}

    - name: Confige VM hardware
      vars:
        vmid_string: "vmid: {{ vmid }}"
      command: >
        qm set {{ vmid }}
          --scsihw virtio-scsi-pci
          --scsi0 {{ disk_storage }}:vm-{{ vmid }}-disk-0,discard=on
          --ide2 {{ disk_storage }}:cloudinit
          --bootdisk scsi0
          --boot c
          --serial0 socket
          --vga serial0

    - name: Resize VM disk
      vars:
        vmid_string: "vmid: {{ vmid }}"
      command: >
        qm resize {{ vmid }} scsi0 {{ disk_size }}G
  when: vmid_string not in vm_list.stdout
