---
- include_tasks: util_vm_status.yml

- block:
  - name: "{{ hostname }} - Shutdown"
    shell: >
      qm shutdown {{ vmid }} && qm wait {{ vmid }} -timeout 60
    when: >
      resource_type == 'vm' and
      'stopped' not in vm_status.stdout

  - name: "{{ hostname }} - Shutdown"
    shell: >
      pct shutdown {{ vmid }}
    when: >
      resource_type == 'ct' and
      'stopped' not in ct_status.stdout
  when: vmid_string in vm_list.stdout
