---
- name: restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: restart hddtemp
  ansible.builtin.service:
    name: hddtemp
    state: restarted
    daemon_reload: yes
