---
- name: Add repository
  ansible.builtin.copy:
    src: files/buster-backports.list
    dest: /etc/apt/sources.list.d
    mode: 0644
  when: ansible_distribution == "Debian" and ansible_distribution_version == "10"

- name: Install packages
  ansible.builtin.package:
    update_cache: true
    state: present
    name:
      - wireguard

- name: Enable kernel module
  community.general.modprobe:
    name: wireguard
    state: present

- name: Enable packet forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    reload: true
    state: present
