---
- name: Add repository
  copy:
    src: files/buster-backports.list
    dest: /etc/apt/sources.list.d
    mode: 0644
  when: ansible_distribution == 'Debian' and ansible_distribution_version == '10'

- name: Install packages
  package:
    update_cache: yes
    state: present
    name:
      - wireguard

- name: Enable kernel module
  modprobe:
    name: wireguard
    state: present

- name: Enable packet forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    reload: yes
    state: present
