---
- name: Install packages
  apt:
    state: present
    name:
      - rsnapshot

- name: Copy configuration
  template:
    src: templates/rsnapshot.conf.j2
    dest: /etc/rsnapshot.conf

- name: Copy cron schedule
  copy:
    src: files/rsnapshot
    dest: /etc/cron.d
